[package]
name = "tokenserver"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
livekit-api = "0.2.0"
serde = "1.0.217"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.12.0", features = [ "v4" ] }
warp = "0.3.7"
